name: Minimal Supported Rust Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.1.0
        with:
          version: "7.3.27"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-msrv
        run: cargo install cargo-msrv

      - name: Verify MSRV
        run: cargo msrv verify -- cargo check --features num-bigint,embedded-fdb-include,tenant-experimental,fdb-7_3 --no-default-features
        working-directory: ./foundationdb

      - name: Find MSRV
        if: failure()
        run: cargo msrv -- cargo check --features num-bigint,embedded-fdb-include,tenant-experimental,fdb-7_3 --no-default-features
        working-directory: ./foundationdb
